<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Impute Missing Values**

Estimated time needed: **30** minutes

In this lab, you will practice essential data wrangling techniques using the Stack Overflow survey dataset. The primary focus is on handling missing data and ensuring data quality. You will:

- **Load the Data:** Import the dataset into a DataFrame using the pandas library.

- **Clean the Data:** Identify and remove duplicate entries to maintain data integrity.

- **Handle Missing Values:** Detect missing values, impute them with appropriate strategies, and verify the imputation to create a complete and reliable dataset for analysis.

This lab equips you with the skills to effectively preprocess and clean real-world datasets, a crucial step in any data analysis project.

## Objectives

In this lab, you will perform the following:

-   Identify missing values in the dataset.

-   Apply techniques to impute missing values in the dataset.
  
-   Use suitable techniques to normalize data in the dataset.

-----

#### Install needed library

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Step 1: Import Required Libraries

In [18]:
import pandas as pd
import numpy as np

### Step 2: Load the Dataset Into a Dataframe

#### **Read Data**
<p>
The functions below will download the dataset into your browser:
</p>

In [3]:
file_path = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(file_path)

# Display the first few rows to ensure it loaded correctly
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

### Step 3. Finding and Removing Duplicates
##### Task 1: Identify duplicate rows in the dataset.

In [4]:
## Write your code here
duplicate_rows = df[df.duplicated()]
num_duplicates = duplicate_rows.shape[0]

num_duplicates

0

##### Task 2: Remove the duplicate rows from the dataframe.

In [5]:
## Write your code here
# There is no duplicate Rows

### Step 4: Finding Missing Values
##### Task 3: Find the missing values for all columns.

In [6]:
## Write your code here
missing_data = df.isnull()
#print(missing_data.head())
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

ResponseId
ResponseId
False    65437
Name: count, dtype: int64

MainBranch
MainBranch
False    65437
Name: count, dtype: int64

Age
Age
False    65437
Name: count, dtype: int64

Employment
Employment
False    65437
Name: count, dtype: int64

RemoteWork
RemoteWork
False    54806
True     10631
Name: count, dtype: int64

Check
Check
False    65437
Name: count, dtype: int64

CodingActivities
CodingActivities
False    54466
True     10971
Name: count, dtype: int64

EdLevel
EdLevel
False    60784
True      4653
Name: count, dtype: int64

LearnCode
LearnCode
False    60488
True      4949
Name: count, dtype: int64

LearnCodeOnline
LearnCodeOnline
False    49237
True     16200
Name: count, dtype: int64

TechDoc
TechDoc
False    40897
True     24540
Name: count, dtype: int64

YearsCode
YearsCode
False    59869
True      5568
Name: count, dtype: int64

YearsCodePro
YearsCodePro
False    51610
True     13827
Name: count, dtype: int64

DevType
DevType
False    59445
True      5992
Name: count, dtype: int64

OrgSize
OrgSize
False    47480
True     17957
Name: count, dtype: int64

PurchaseInfluence
PurchaseInfluence
False    47406
True     18031
Name: count, dtype: int64

BuyNewTool
BuyNewTool
False    45181
True     20256
Name: count, dtype: int64

BuildvsBuy
BuildvsBuy
False    43358
True     22079
Name: count, dtype: int64

TechEndorse
TechEndorse
False    43668
True     21769
Name: count, dtype: int64

Country
Country
False    58930
True      6507
Name: count, dtype: int64

Currency
Currency
False    46684
True     18753
Name: count, dtype: int64

CompTotal
CompTotal
False    33740
True     31697
Name: count, dtype: int64

LanguageHaveWorkedWith
LanguageHaveWorkedWith
False    59745
True      5692
Name: count, dtype: int64

LanguageWantToWorkWith
LanguageWantToWorkWith
False    55752
True      9685
Name: count, dtype: int64

LanguageAdmired
LanguageAdmired
False    50872
True     14565
Name: count, dtype: int64

DatabaseHaveWorkedWith
DatabaseHaveWorkedWith
False    50254
True     15183
Name: count, dtype: int64

DatabaseWantToWorkWith
DatabaseWantToWorkWith
False    42558
True     22879
Name: count, dtype: int64

DatabaseAdmired
DatabaseAdmired
False    38557
True     26880
Name: count, dtype: int64

PlatformHaveWorkedWith
PlatformHaveWorkedWith
False    42366
True     23071
Name: count, dtype: int64

PlatformWantToWorkWith
PlatformWantToWorkWith
False    34532
True     30905
Name: count, dtype: int64

PlatformAdmired
PlatformAdmired
True     34060
False    31377
Name: count, dtype: int64

WebframeHaveWorkedWith
WebframeHaveWorkedWith
False    45161
True     20276
Name: count, dtype: int64

WebframeWantToWorkWith
WebframeWantToWorkWith
False    38535
True     26902
Name: count, dtype: int64

WebframeAdmired
WebframeAdmired
False    34943
True     30494
Name: count, dtype: int64

EmbeddedHaveWorkedWith
EmbeddedHaveWorkedWith
True     43223
False    22214
Name: count, dtype: int64

EmbeddedWantToWorkWith
EmbeddedWantToWorkWith
True     47837
False    17600
Name: count, dtype: int64

EmbeddedAdmired
EmbeddedAdmired
True     48704
False    16733
Name: count, dtype: int64

MiscTechHaveWorkedWith
MiscTechHaveWorkedWith
False    39443
True     25994
Name: count, dtype: int64

MiscTechWantToWorkWith
MiscTechWantToWorkWith
False    32964
True     32473
Name: count, dtype: int64

MiscTechAdmired
MiscTechAdmired
True     35841
False    29596
Name: count, dtype: int64

ToolsTechHaveWorkedWith
ToolsTechHaveWorkedWith
False    52482
True     12955
Name: count, dtype: int64

ToolsTechWantToWorkWith
ToolsTechWantToWorkWith
False    46084
True     19353
Name: count, dtype: int64

ToolsTechAdmired
ToolsTechAdmired
False    43997
True     21440
Name: count, dtype: int64

NEWCollabToolsHaveWorkedWith
NEWCollabToolsHaveWorkedWith
False    57592
True      7845
Name: count, dtype: int64

NEWCollabToolsWantToWorkWith
NEWCollabToolsWantToWorkWith
False    52087
True     13350
Name: count, dtype: int64

NEWCollabToolsAdmired
NEWCollabToolsAdmired
False    50711
True     14726
Name: count, dtype: int64

OpSysPersonal use
OpSysPersonal use
False    58174
True      7263
Name: count, dtype: int64

OpSysProfessional use
OpSysProfessional use
False    52973
True     12464
Name: count, dtype: int64

OfficeStackAsyncHaveWorkedWith
OfficeStackAsyncHaveWorkedWith
False    48093
True     17344
Name: count, dtype: int64

OfficeStackAsyncWantToWorkWith
OfficeStackAsyncWantToWorkWith
False    38966
True     26471
Name: count, dtype: int64

OfficeStackAsyncAdmired
OfficeStackAsyncAdmired
False    37204
True     28233
Name: count, dtype: int64

OfficeStackSyncHaveWorkedWith
OfficeStackSyncHaveWorkedWith
False    55545
True      9892
Name: count, dtype: int64

OfficeStackSyncWantToWorkWith
OfficeStackSyncWantToWorkWith
False    46711
True     18726
Name: count, dtype: int64

OfficeStackSyncAdmired
OfficeStackSyncAdmired
False    44712
True     20725
Name: count, dtype: int64

AISearchDevHaveWorkedWith
AISearchDevHaveWorkedWith
False    44453
True     20984
Name: count, dtype: int64

AISearchDevWantToWorkWith
AISearchDevWantToWorkWith
False    36701
True     28736
Name: count, dtype: int64

AISearchDevAdmired
AISearchDevAdmired
False    35543
True     29894
Name: count, dtype: int64

NEWSOSites
NEWSOSites
False    60286
True      5151
Name: count, dtype: int64

SOVisitFreq
SOVisitFreq
False    59536
True      5901
Name: count, dtype: int64

SOAccount
SOAccount
False    59560
True      5877
Name: count, dtype: int64

SOPartFreq
SOPartFreq
False    45237
True     20200
Name: count, dtype: int64

SOHow
SOHow
False    58962
True      6475
Name: count, dtype: int64

SOComm
SOComm
False    59163
True      6274
Name: count, dtype: int64

AISelect
AISelect
False    60907
True      4530
Name: count, dtype: int64

AISent
AISent
False    45873
True     19564
Name: count, dtype: int64

AIBen
AIBen
False    36894
True     28543
Name: count, dtype: int64

AIAcc
AIAcc
False    37302
True     28135
Name: count, dtype: int64

AIComplex
AIComplex
False    37021
True     28416
Name: count, dtype: int64

AIToolCurrently Using
AIToolCurrently Using
False    35072
True     30365
Name: count, dtype: int64

AIToolInterested in Using
AIToolInterested in Using
True     34746
False    30691
Name: count, dtype: int64

AIToolNot interested in Using
AIToolNot interested in Using
True     41023
False    24414
Name: count, dtype: int64

AINextMuch more integrated
AINextMuch more integrated
True     51999
False    13438
Name: count, dtype: int64

AINextNo change
AINextNo change
True     52939
False    12498
Name: count, dtype: int64

AINextMore integrated
AINextMore integrated
True     41009
False    24428
Name: count, dtype: int64

AINextLess integrated
AINextLess integrated
True     63082
False     2355
Name: count, dtype: int64

AINextMuch less integrated
AINextMuch less integrated
True     64289
False     1148
Name: count, dtype: int64

AIThreat
AIThreat
False    44689
True     20748
Name: count, dtype: int64

AIEthics
AIEthics
False    41548
True     23889
Name: count, dtype: int64

AIChallenges
AIChallenges
False    37531
True     27906
Name: count, dtype: int64

TBranch
TBranch
False    44477
True     20960
Name: count, dtype: int64

ICorPM
ICorPM
True     35636
False    29801
Name: count, dtype: int64

WorkExp
WorkExp
True     35779
False    29658
Name: count, dtype: int64

Knowledge_1
Knowledge_1
True     36773
False    28664
Name: count, dtype: int64

Knowledge_2
Knowledge_2
True     37416
False    28021
Name: count, dtype: int64

Knowledge_3
Knowledge_3
True     37342
False    28095
Name: count, dtype: int64

Knowledge_4
Knowledge_4
True     37407
False    28030
Name: count, dtype: int64

Knowledge_5
Knowledge_5
True     37557
False    27880
Name: count, dtype: int64

Knowledge_6
Knowledge_6
True     37573
False    27864
Name: count, dtype: int64

Knowledge_7
Knowledge_7
True     37659
False    27778
Name: count, dtype: int64

Knowledge_8
Knowledge_8
True     37679
False    27758
Name: count, dtype: int64

Knowledge_9
Knowledge_9
True     37802
False    27635
Name: count, dtype: int64

Frequency_1
Frequency_1
True     37068
False    28369
Name: count, dtype: int64

Frequency_2
Frequency_2
True     37073
False    28364
Name: count, dtype: int64

Frequency_3
Frequency_3
True     37727
False    27710
Name: count, dtype: int64

TimeSearching
TimeSearching
True     36526
False    28911
Name: count, dtype: int64

TimeAnswering
TimeAnswering
True     36593
False    28844
Name: count, dtype: int64

Frustration
Frustration
True     37186
False    28251
Name: count, dtype: int64

ProfessionalTech
ProfessionalTech
True     37673
False    27764
Name: count, dtype: int64

ProfessionalCloud
ProfessionalCloud
True     36946
False    28491
Name: count, dtype: int64

ProfessionalQuestion
ProfessionalQuestion
True     36630
False    28807
Name: count, dtype: int64

Industry
Industry
True     36579
False    28858
Name: count, dtype: int64

JobSatPoints_1
JobSatPoints_1
True     36113
False    29324
Name: count, dtype: int64

JobSatPoints_4
JobSatPoints_4
True     36044
False    29393
Name: count, dtype: int64

JobSatPoints_5
JobSatPoints_5
True     36026
False    29411
Name: count, dtype: int64

JobSatPoints_6
JobSatPoints_6
True     35987
False    29450
Name: count, dtype: int64

JobSatPoints_7
JobSatPoints_7
True     35989
False    29448
Name: count, dtype: int64

JobSatPoints_8
JobSatPoints_8
True     35981
False    29456
Name: count, dtype: int64

JobSatPoints_9
JobSatPoints_9
True     35981
False    29456
Name: count, dtype: int64

JobSatPoints_10
JobSatPoints_10
True     35987
False    29450
Name: count, dtype: int64

JobSatPoints_11
JobSatPoints_11
True     35992
False    29445
Name: count, dtype: int64

SurveyLength
SurveyLength
False    56182
True      9255
Name: count, dtype: int64

SurveyEase
SurveyEase
False    56238
True      9199
Name: count, dtype: int64

ConvertedCompYearly
ConvertedCompYearly
True     42002
False    23435
Name: count, dtype: int64

JobSat
JobSat
True     36311
False    29126
Name: count, dtype: int64

##### Task 4: Find out how many rows are missing in the column RemoteWork.

In [10]:
## Write your code here
df['RemoteWork'].isnull().value_counts()

RemoteWork
False    54806
True     10631
Name: count, dtype: int64

### Step 5. Imputing Missing Values
##### Task 5: Find the value counts for the column RemoteWork.

In [12]:
## Write your code here
count_RW = df.groupby ('RemoteWork')['RemoteWork'].value_counts()
count_RW

RemoteWork
Hybrid (some remote, some in-person)    23015
In-person                               10960
Remote                                  20831
Name: count, dtype: int64

##### Task 6: Identify the most frequent (majority) value in the RemoteWork column.

In [15]:
## Write your code here
print(count_RW.idxmax(),count_RW.max())

Hybrid (some remote, some in-person) 23015

##### Task 7: Impute (replace) all the empty rows in the column RemoteWork with the majority value.

In [19]:
## Write your code here
most_RW = count_RW.idxmax()
df['RemoteWork'].replace(np.nan, most_RW, inplace=True)

df['RemoteWork'].isnull().value_counts()

/tmp/ipykernel_2591/2484625077.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RemoteWork'].replace(np.nan, most_RW, inplace=True)

RemoteWork
False    65437
Name: count, dtype: int64

##### Task 8: Check for any compensation-related columns and describe their distribution.

In [20]:
## Write your code here
count_Industry = df.groupby ('Industry')['Industry'].value_counts()
count_Industry

Industry
Banking/Financial Services                     1371
Computer Systems Design and Services            844
Energy                                          578
Fintech                                        1641
Government                                      962
Healthcare                                     1277
Higher Education                                890
Insurance                                       389
Internet, Telecomm or Information Services     1629
Manufacturing                                  1265
Media & Advertising Services                    894
Other:                                         3077
Retail and Consumer Services                   1264
Software Development                          11918
Transportation, or Supply Chain                 859
Name: count, dtype: int64

### Summary

**In this lab, you focused on imputing missing values in the dataset.**

- Use the <code>pandas.read_csv()</code> function to load a dataset from a CSV file into a DataFrame.

- Download the dataset if it's not available online and specify the correct file path.

<!--
## Change Log
|Date (YYYY-MM-DD)|Version|Changed By|Change Description|
|-|-|-|-|
|2024-11-05|1.3|Madhusudhan Moole|Updated lab|
|2024-10-29|1.2|Madhusudhan Moole|Updated lab|
|2024-09-27|1.1|Madhusudhan Moole|Updated lab|
|2024-09-26|1.0|Raghul Ramesh|Created lab|
--!>

Copyright © IBM Corporation. All rights reserved.